[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/family-law-lp"
  to = "/family-law-lp.html"
  status = 200

[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200
